[workspace]
members = ["macros"]

[package]
name = "clickhouse-client"
version = "0.10.0"
edition = "2021"
description = "Client for Clickhouse DB"
license = "MIT OR Apache-2.0"
repository = "https://github.com/nlargueze/clickhouse-client"

[features]
default = ["time", "uuid"]
time = ["dep:time"]
uuid = ["dep:uuid"]

[dependencies]
async-trait = "0.1.68"
clickhouse-client-macros = { version = "0.8.0", path = "./macros" }
hyper = { version = "0.14.26", features = ["client", "http1"] }
hyper-rustls = "0.24.0"
thiserror = "1.0.40"
time = { version = "0.3.20", optional = true, features = [
    "formatting",
    "serde",
    "macros",
    "parsing",
] }
tracing = "0.1.37"
uuid = { version = "1.3.3", optional = true }

[dev-dependencies]
tokio = { version = "1.28.0", features = ["full"] }
tracing-ext = "0.2.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
